import type { Bot } from "grammy";
import { type HistoryEntry } from "../auto-reply/reply/history.js";
import type { MsgContext } from "../auto-reply/templating.js";
import { type StatusReactionController } from "../channels/status-reactions.js";
import type { OpenClawConfig } from "../config/config.js";
import type { DmPolicy, TelegramGroupConfig, TelegramTopicConfig } from "../config/types.js";
import type { StickerMetadata, TelegramContext } from "./bot/types.js";
export type TelegramMediaRef = {
    path: string;
    contentType?: string;
    stickerMetadata?: StickerMetadata;
};
type TelegramMessageContextOptions = {
    forceWasMentioned?: boolean;
    messageIdOverride?: string;
};
type TelegramLogger = {
    info: (obj: Record<string, unknown>, msg: string) => void;
};
type ResolveTelegramGroupConfig = (chatId: string | number, messageThreadId?: number) => {
    groupConfig?: TelegramGroupConfig;
    topicConfig?: TelegramTopicConfig;
};
type ResolveGroupActivation = (params: {
    chatId: string | number;
    agentId?: string;
    messageThreadId?: number;
    sessionKey?: string;
}) => boolean | undefined;
type ResolveGroupRequireMention = (chatId: string | number) => boolean;
export type BuildTelegramMessageContextParams = {
    primaryCtx: TelegramContext;
    allMedia: TelegramMediaRef[];
    storeAllowFrom: string[];
    options?: TelegramMessageContextOptions;
    bot: Bot;
    cfg: OpenClawConfig;
    account: {
        accountId: string;
    };
    historyLimit: number;
    groupHistories: Map<string, HistoryEntry[]>;
    dmPolicy: DmPolicy;
    allowFrom?: Array<string | number>;
    groupAllowFrom?: Array<string | number>;
    ackReactionScope: "off" | "group-mentions" | "group-all" | "direct" | "all";
    logger: TelegramLogger;
    resolveGroupActivation: ResolveGroupActivation;
    resolveGroupRequireMention: ResolveGroupRequireMention;
    resolveTelegramGroupConfig: ResolveTelegramGroupConfig;
};
export declare const buildTelegramMessageContext: ({ primaryCtx, allMedia, storeAllowFrom, options, bot, cfg, account, historyLimit, groupHistories, dmPolicy, allowFrom, groupAllowFrom, ackReactionScope, logger, resolveGroupActivation, resolveGroupRequireMention, resolveTelegramGroupConfig, }: BuildTelegramMessageContextParams) => Promise<{
    ctxPayload: {
        CommandAuthorized: boolean;
        MessageThreadId: number;
        IsForum: boolean;
        OriginatingChannel: "telegram";
        OriginatingTo: string;
        LocationLat: number;
        LocationLon: number;
        LocationAccuracy?: number;
        LocationName?: string;
        LocationAddress?: string;
        LocationSource: import("../channels/location.js").LocationSource;
        LocationIsLive: boolean;
        Body: string;
        BodyForAgent: string;
        InboundHistory: {
            sender: string;
            body: string;
            timestamp: number;
        }[];
        RawBody: string;
        CommandBody: string;
        From: string;
        To: string;
        SessionKey: string;
        AccountId: string;
        ChatType: string;
        ConversationLabel: string;
        GroupSubject: string;
        GroupSystemPrompt: string;
        SenderName: string;
        SenderId: string;
        SenderUsername: string;
        Provider: string;
        Surface: string;
        MessageSid: string;
        ReplyToId: string;
        ReplyToBody: string;
        ReplyToSender: string;
        ReplyToIsQuote: boolean;
        ReplyToForwardedFrom: string;
        ReplyToForwardedFromType: string;
        ReplyToForwardedFromId: string;
        ReplyToForwardedFromUsername: string;
        ReplyToForwardedFromTitle: string;
        ReplyToForwardedDate: number;
        ForwardedFrom: string;
        ForwardedFromType: string;
        ForwardedFromId: string;
        ForwardedFromUsername: string;
        ForwardedFromTitle: string;
        ForwardedFromSignature: string;
        ForwardedFromChatType: "group" | "channel" | "private" | "supergroup";
        ForwardedFromMessageId: number;
        ForwardedDate: number;
        Timestamp: number;
        WasMentioned: boolean;
        MediaPath: string;
        MediaType: string;
        MediaUrl: string;
        MediaPaths: string[];
        MediaUrls: string[];
        MediaTypes: string[];
        Sticker: StickerMetadata;
    } & Omit<MsgContext, "CommandAuthorized"> & {
        CommandAuthorized: boolean;
    };
    primaryCtx: TelegramContext;
    msg: import("@grammyjs/types").Message;
    chatId: number;
    isGroup: boolean;
    resolvedThreadId: number;
    threadSpec: import("./bot/helpers.js").TelegramThreadSpec;
    replyThreadId: number;
    isForum: boolean;
    historyKey: string;
    historyLimit: number;
    groupHistories: Map<string, HistoryEntry[]>;
    route: import("../routing/resolve-route.js").ResolvedAgentRoute;
    skillFilter: string[];
    sendTyping: () => Promise<void>;
    sendRecordVoice: () => Promise<void>;
    ackReactionPromise: Promise<boolean>;
    reactionApi: any;
    removeAckAfterReply: boolean;
    statusReactionController: StatusReactionController;
    accountId: string;
}>;
export type TelegramMessageContext = NonNullable<Awaited<ReturnType<typeof buildTelegramMessageContext>>>;

